[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --alluredir=reports/allure-results --clean-alluredir
markers =
    smoke: 冒烟测试
    regression: 回归测试
